### ISSUE TITLE
Missing requirements.txt in PyPI package for pixell 0.9.0?

### ISSUE THREAD

**Issue by mattyowl** [simonsobs/pixell#101]
* pixell version: 0.9.0
* Python version: 3.6.9
* Operating System: Ubuntu 18.04

### Description

Nemo installs pixell via PyPI in the standard manner. Since I did a new installation on a machine without pixell already installed, it pulled the latest version of pixell (0.9.0) from PyPI compared to the version I have installed on other machines (the Nemo setup.py script just specifies "pixell >= 0.5", so elsewhere pixell hasn't been updated for a while).

### What I Did

```
<in nemo source code dir - i.e., running nemo setup.py script>
% sudo python3 setup.py install

Output:
<nemo install stuff cut here>

Installed /usr/local/lib/python3.6/dist-packages/nemo-0.2.0-py3.6-linux-x86_64.egg
Processing dependencies for nemo==0.2.0
Searching for pixell>=0.5
Reading https://pypi.python.org/simple/pixell/
Downloading https://files.pythonhosted.org/packages/65/e6/088bc7766f875d406033181672497ef07075b7df497f4259b57946d3513f/pixell-0.9.0.tar.gz#sha256=6c4e86339f080d1c3fbf85105d94cf45e201337dcbcd4c28d32da5abe27b73aa
Best match: pixell 0.9.0
Processing pixell-0.9.0.tar.gz
Writing /tmp/easy_install-dvrz4nnp/pixell-0.9.0/setup.cfg
Running pixell-0.9.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-dvrz4nnp/pixell-0.9.0/egg-dist-tmp-ovzwcx54
error: [Errno 2] No such file or directory: 'requirements.txt'

```

**Comment by mattyowl** [comment]
Unsurprisingly, the same result happens if doing:

```
sudo pip3 install pixell
```

**Comment by msyriac** [comment]
My bad, pixell 0.9.0 should never have existed. It was pushed to PyPI accidentally yesterday during my investigation into #94 . I've yanked it from PyPI. I don't understand why the requirements.txt issue cropped up, but I'd re-try this with the latest stable release on PyPI (0.7.0).

**Comment by msyriac** [comment]
I'm fairly confident this issue can't arise with v0.9.6, so closing it, but let me know if it does!
