### ISSUE TITLE
downgraded maps cause issues with map2alm

### ISSUE THREAD

**Issue by AdriJD** [simonsobs/pixell#164]
* pixell version: 0.14.0
* Python version: 3.8.0
* Operating System: Springdale Linux 7.9 (Verona) (Princeton Tiger cluster)

### Description

The `curvedsky.map2alm()` operation does not work correctly for enmaps that are downgraded using `enmap.dowgrade`. It looks like there is a small pixel shift introduced in the downgrade operation that leads to this behavior. In the example below I can make the operation work correctly again by manually subtracting 0.25 from the `wcs.wcs.crpix` value of the downgraded map.

The same happens for other map geometries, like those of the DR6 maps (although there I have to add 0.25 to `wcs.wcs.crpix`). The same happens with double precision. The same happens with older pixell versions.

I took a look at `wcsutils.scale()`, which has the following lines:
```
if not corner:
    wcs.wcs.crpix -= 0.5
wcs.wcs.crpix *= scale
wcs.wcs.cdelt /= scale
if not corner:
    wcs.wcs.crpix += 0.5
```
Perhaps the `0.5` value here is applied incorrectly?

### What I Did

```
import numpy as np
import os

from pixell import sharp, enmap, enplot, curvedsky, utils
                                                                       
opj = os.path.join
imgdir = '/home/adriaand/project/actpol/20210915_mnms_alm'

# Set lmax and create a sim with a red spectrum.                                                                                                          
lmax = 1000
ells = np.arange(lmax + 1)
cov_ell = np.zeros((1, 1, lmax + 1))
cov_ell[...,1:] = (ells[1:] / 200) ** -2 * 0.1
alm, ainfo = curvedsky.rand_alm(cov_ell, return_ainfo=True)                                                                         
alm = alm.astype(np.complex64)
alm_out = alm.copy()

# Allocate full-sky map with enough pixels to support lmax.
imap = curvedsky.make_projectable_map_by_pos(
    [[np.pi/2, -np.pi/2],[-np.pi, np.pi]], 4 * lmax, dims=(1,))                                                                            
imap = imap.astype(np.float32)
omap = imap.copy()

# Go to map space and then do map2alm -> alm2map.
curvedsky.alm2map(alm, imap, ainfo=ainfo)
curvedsky.map2alm(imap, alm_out, ainfo=ainfo)
curvedsky.alm2map(alm_out, omap, ainfo=ainfo)

# Compare to input.
plot = enplot.plot(imap, colorbar=True, grid=False, downgrade=1, font_size=200)
enplot.write(opj(imgdir, 'imap'), plot)

plot = enplot.plot(omap, colorbar=True, grid=False, downgrade=1, font_size=200)
enplot.write(opj(imgdir, 'omap'), plot)

plot = enplot.plot(imap - omap, colorbar=True, grid=False, downgrade=1, font_size=200)
enplot.write(opj(imgdir, 'diff'), plot)

# Now downgrade by 2 and repeat.
imap = enmap.downgrade(imap, 2)
omap = imap.copy()

curvedsky.alm2map(alm, imap, ainfo=ainfo)
curvedsky.map2alm(imap, alm_out, ainfo=ainfo)
curvedsky.alm2map(alm_out, omap, ainfo=ainfo)

plot = enplot.plot(imap, colorbar=True, grid=False, downgrade=1, font_size=100)
enplot.write(opj(imgdir, 'dg2_imap'), plot)

plot = enplot.plot(omap, colorbar=True, grid=False, downgrade=1, font_size=100)
enplot.write(opj(imgdir, 'dg2_omap'), plot)

plot = enplot.plot(imap - omap, colorbar=True, grid=False, downgrade=1, font_size=100)
enplot.write(opj(imgdir, 'dg2_diff'), plot)

# Finally, repeat, but manually correct the wcs info.
imap.wcs.wcs.crpix[0] -= 0.25
imap.wcs.wcs.crpix[1] -= 0.25
omap = imap.copy()

curvedsky.alm2map(alm, imap, ainfo=ainfo)
curvedsky.map2alm(imap, alm_out, ainfo=ainfo)
curvedsky.alm2map(alm_out, omap, ainfo=ainfo)

plot = enplot.plot(imap, colorbar=True, grid=False, downgrade=1, font_size=100)
enplot.write(opj(imgdir, 'dg2_corr_imap'), plot)

plot = enplot.plot(omap, colorbar=True, grid=False, downgrade=1, font_size=100)
enplot.write(opj(imgdir, 'dg2_corr_omap'), plot)

plot = enplot.plot(imap - omap, colorbar=True, grid=False, downgrade=1, font_size=100)
enplot.write(opj(imgdir, 'dg2_corr_diff'), plot)
```
Here are jpgs of the difference plots in order of generation:

The difference map when no downgrade is applied:
![simple_diff_0](https://user-images.githubusercontent.com/14160114/140628742-cddc5747-8d9d-4841-9bca-e000339d915d.jpg)

The difference map when downgrade of 2 is applied:
![simple_dg2_diff_0](https://user-images.githubusercontent.com/14160114/140628745-58c7defc-390b-4ae0-91e4-d7168ac42512.jpg)

The difference map when downgrade of 2 is applied and the `wcs.wcs.crpix` is manually corrected:
![simple_dg2_corr_diff_0](https://user-images.githubusercontent.com/14160114/140628750-06eacf13-6e84-4cd9-88ad-d01716368a43.jpg)

Here is a zoomed version of the middle of the second plot:

<img width="609" alt="simple_dg2_diff_0_zoom" src="https://user-images.githubusercontent.com/14160114/140628754-ebb03165-f6f4-475b-969a-5c1a27bd10f3.png">

This is a jpg of the input map:
![simple_imap_0](https://user-images.githubusercontent.com/14160114/140628855-bdcfea98-78f3-4a8a-a4ef-ee2ca3e6527b.jpg)

**Comment by amaurea** [comment]
This was due to the downgraded map not having an exact quadrature available. I've now changed the behavior of map2alm to raise an exception instead of silently shifting the map to match the closest existing quadratures. To make it do that, one now has to explicitly pass in the tweak=True argument. The same argument can be passed to alm2map, letting them stay inverses of each other even when using this approximation.

I think this is a good solution to the problem, even though it means that some code that currently works may need to have some tweak=True arguments added to stay working. I made the exception that's raised spell this out.
