### ISSUE TITLE
argparse changes with Python 3.10

### ISSUE THREAD

**Issue by xgarrido** [simonsobs/pixell#175]
* pixell version: 0.14.3
* Python version: 3.10.1
* Operating System: Linux

### Description

Starting from python 3.10, the `argparse` library has changed the name of "optional arguments" to "options" (switch between versions 3.9 and 3.10 in this page https://docs.python.org/3.10/library/argparse.html) 

When loading the `enplot` component of `pixell`, it fails due to this line https://github.com/simonsobs/pixell/blob/master/pixell/enplot.py#L311 since splitting wrt to "optional arguments:" does not work anymore. It raises an `IndexError` 

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-28ac1dd88d45> in <module>
----> 1 help_long = "\n\t".join(arg_parser.format_help().split("optional arguments:")[1].split("\n"))

IndexError: list index out of range
```

### What I Did

A fix will be to do something like

```
help_long = "\n\t".join(arg_parser.format_help().split("optional arguments:" if sys.version_info < (3, 10) else "options:")[1].split("\n"))
```
ensuring backward compatibility.

**Comment by msyriac** [comment]
Thanks Xavier @xgarrido ! Any chance you could PR this quick? I'll add Python 3.10 to tests in the meantime.
