### ISSUE TITLE
Compiling on mac osx

### ISSUE THREAD

**Issue by jodunkley** [simonsobs/pixell#18]
To get it to compile on Mac osx I needed these two things:

$ LDFLAGS="$LDFLAGS -undefined dynamic_lookup -bundle"

before running setup.py

And I had to remove instances of 'fopenmp' by hand from setup.py (likely my own local problem with openmp)

**Comment by jaguirre** [comment]
Long time listener, first time caller.  My laptop is MacOS High Sierra 10.13.6, with Anaconda python 3 as my python install. Did:

git clone https://github.com/simonsobs/sotools.git
cd sotools
git checkout osx_tests
python setup.py install 
< bunch of warnings > 
Finished processing dependencies for sotools==0.1.0

import sotools works without error 

Now to try to do something ...

**Comment by jaguirre** [comment]
jaguirre is an idiot.  push the green button, James!

**Comment by msyriac** [comment]
Thanks @jodunkley and @jaguirre for trying it out. Couple of things:

1. Sometimes it can look like the install worked. "import sotools" is not exhaustive enough to check that everything installed correctly. The best thing to do is run "py.test" in the git cloned directory. The second best thing to do is try "from sotools import sharp ; from sotools import interpol" (these are the 2 compiled modules) from your home directory.

2. Having openmp work is important for performance I think. My guess is that Macs default to the "clang" compiler, and typically have a version that doesn't support openmp. So if you see the word "clang" pop up in the setup.py output, let me know. I'm trying to figure out a way to force setup.py to NOT use the clang compiler.

3. The osx branch is not different from the master branch as far as setup.py goes. (It is generally behind master in terms of being up-to-date). I'm using that branch to experiment with OS X on the remote server (Travis). So if you're on a Mac, please still use the master branch. Sorry for the confusion.

**Comment by mhasself** [comment]
Mat, they're looking at the osx_tests branch that I created (sorry for the name crash), which does have adjustments to setup.py.

**Comment by msyriac** [comment]
Ah, I'm sorry Matthew! Yes, please do look at the osx_tests branch @jodunkley and @jaguirre !

**Comment by jaguirre** [comment]
Ah, the plot thickens.  So looking more closely (and just doing a fresh install of everything), I see the following:

- clang doesn't appear in the output of `python setup.py install`
- openmp looks like it is just skipped: `checking for gcc option to support OpenMP... unsupported`
- lib sharp _looks_ like it is being compiled `#  compiling libsharp/sharp_testsuite.c`, though there are some warnings like `ld: warning: object file (_deps/libsharp/auto/lib/libsharp.a(sharp.o)) was built for newer OSX version (10.13) than being linked (10.9)`

but when running py.test, I get

`    from sotools import sharp
E   ImportError: cannot import name 'sharp'`

**Comment by jodunkley** [comment]
>The second best thing to do is try "from sotools import sharp ; from sotools import interpol" (these are the 2 compiled modules) from your home directory.
This works for me in my home directory. For libsharp I installed it myself and have a symlink to _deps as suggested.

>So if you see the word "clang" pop up in the setup.py output, let me know.
Same for James - it doesn't appear in my output.

(Haven't tested the new osx_tests branch or py.test yet)

**Comment by jodunkley** [comment]
ah, but when I run py.test in the git cloned directory I do get the same error as James. I'll look at this again later.

**Comment by jodunkley** [comment]
and 'from sotools import sharp' and  'from sotools import interpol' seems to work for me in every directory I have tried, but just gives the error message when I'm in the git cloned directory sotools.

**Comment by jaguirre** [comment]
whoa - I didn't bother trying after py.test failed, but, yes likewise - both imports succeed without error.


James Aguirre

Associate Professor

Department of Physics and Astronomy

University of Pennsylvania

David Rittenhouse Laboratory 4N4b

209 South 33rd Street Philadelphia, PA 19104

(215) 898-9596 (office)

(215) 898-9646 (lab)

jaguirre@sas.upenn.edu

http://www.sas.upenn.edu/~jaguirre/

________________________________

**Comment by msyriac** [comment]
If you get errors from calling py.test this way, please feel free to paste them here. (Do a git pull on master just to be safe, since I've disabled some known failing tests just now)

**Comment by mhasself** [comment]
@msyriac : all the osx_test branch does is to incorporate the flag adjustments that Jo recommended, to be the default on platform='darwin'!  So I don't think jodunkley's build worked "without" the tweaks...

py.test doesn't work for me, but that seems unrelated to sotools... which makes me wonder about py.test.  Is "make test" an acceptable test?

For everyone: if you install using "python setup.py install" then you should expect "from sotools import sharp" to work everywhere _except_ within the cloned repo.  If you use "python setup.py develop", or if you run "make test", then there may be a local copy in the cloned repo that will be fully functional.

**Comment by msyriac** [comment]
Ok, got it, so not suprising that it worked for Jo.

@mhasself , I really do like the simplicity of the py.test framework. Could you expand on how it broke for you?

**Comment by mhasself** [comment]
py.test failed for me because some random library I have has hooked into it, and that had a dependency which wasn't installed.  Once I fixed that, it choked on _deps/libsharp.  If I run "py.test tests", it runs the tests and they pass.

However -- I checked that this will only work if one has built the library *in place*.  That is not done, by default, if you run "setup.py install".  You have to run "setup.py build_ext -i", or "setup.py develop", or similar.  I do not think that we should instruct *users* to build the library in place.  Rather, we should instruct them to "install" it.  And so, we should also not have them rely on "py.test tests" to test the library in this way.

**Comment by msyriac** [comment]
Ok, got it, I'm going to open a separate issue to decide on the best way to let "users" (not just developers) run tests.

**Comment by ianlowe13** [comment]
Hi all,
Some notes as I am trying to compile/install this from mac osx 10.13.6
- clang pops up right around where it errors out
- for some reason the install script cannot seem to find my libsharp, build from git, but currently living in a git repo
`compile options: '-I//anaconda/lib/python2.7/site-packages/numpy/core/include -I//anaconda/lib/python2.7/site-packages/numpy/core/include -I_deps/libsharp/auto/include -I//anaconda/include/python2.7 -c'
extra options: '-std=c99 -Wno-strict-aliasing'
gcc -bundle -undefined dynamic_lookup -L//anaconda/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.6-x86_64-2.7/cython/sharp.o -L_deps/libsharp/auto/lib -L//anaconda/lib -lsharp -lc_utils -lfftpack -o build/lib.macosx-10.6-x86_64-2.7/sotools/sharp.so -undefined dynamic_lookup -bundle
ld: warning: directory not found for option '-L_deps/libsharp/auto/lib'
ld: library not found for -lsharp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ld: warning: directory not found for option '-L_deps/libsharp/auto/lib'
ld: library not found for -lsharp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: Command "gcc -bundle -undefined dynamic_lookup -L//anaconda/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.6-x86_64-2.7/cython/sharp.o -L_deps/libsharp/auto/lib -L//anaconda/lib -lsharp -lc_utils -lfftpack -o build/lib.macosx-10.6-x86_64-2.7/sotools/sharp.so -undefined dynamic_lookup -bundle" failed with exit status 1
`
Any  thoughts?

**Comment by ianlowe13** [comment]
For what its worth, I fixed this by manually building libsharp in the sotools _deps repo and the pythons cript has not killed itself. Apparently my symlink was improperly created for my libsharp installation.

**Comment by msyriac** [comment]
@ianlowe13 Great! Does "from sotools import sharp"  and "from sotools import interpol" work from your home directory?

**Comment by ianlowe13** [comment]
Yeah after I went through and got that setup to work I cd ~ , ipython, and both of those didn't error out at the very least. On a side note, I ran into a whole bunch of other issues that may be relevant to osx users as upgrading to 10.13 sometimes moves usr/include to usr/local/include and gives you a separate usr/include so llvm also needed to be reinstalled for me.

**Comment by msyriac** [comment]
No showstoppers here on Mac installation, so I'm closing this issue.
