### ISSUE TITLE
distutils will be deprecated with Python 3.12

### ISSUE THREAD

**Issue by msyriac** [simonsobs/pixell#198]

**Comment by JBorrow** [comment]
Are there any preferences between meson or scikit-build-core? I am leaning towards meson as it's a more generic build system and does use CMake which I absolutely hate.

https://numpy.org/devdocs/reference/distutils_status_migration.html

**Comment by JBorrow** [comment]
This should also address https://github.com/simonsobs/pixell/issues/33

**Comment by JBorrow** [comment]
Decided on using Meson
