### ISSUE TITLE
enmap.fullsky_geometry mixes up order of res argument when constructing crval

### ISSUE THREAD

**Issue by zatkins2** [simonsobs/pixell#203]
* pixell version: 0.15.1
* Python version: 3.8.3
* Operating System: Springdale 8.6

### Description

`res` is supplied in (dec, ra) order, but wcs assumes (x, y) pixel ordering. Most of `fullsky_geometry` respects this flip-flop, except this [line](https://github.com/simonsobs/pixell/blob/416374022918e73002c7ccb3556eb065ef292ac6/pixell/enmap.py#L1387):
```
wcs.wcs.crval = [res[0]/2/utils.degree,0]
```
where the x-value of `crval` is being set by the `dec` value of `res`. It should be changed to:
```
wcs.wcs.crval = [res[1]/2/utils.degree,0]
```

Of course, this only matters in the case that the `res` of the pixels differs between x and y. In the common situation that `res` is supplied as a single number for both x and y, this issue won't matter.

**Comment by amaurea** [comment]
This should be fixed with the latest commit: #204
