### ISSUE TITLE
Default compiler optimization flag for older gfortran versions

### ISSUE THREAD

**Issue by mattyowl** [simonsobs/pixell#21]
* pixell version: git
* Python version: 3.6.5
* Operating System: Red Hat Enterprise Linux Server release 6.10 (Santiago)

### Description

Default compiler option in the setup.py file isn't understood by older gfortran versions

### What I Did

Running `python setup.py install` etc. on a machine with gfortran version 4.4.7 gives the following error message:

```
f951: error: invalid option argument ‘-Ofast’
error: Command "/usr/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops -Ibuild/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/pixell -I/home/matth/local/lib/python3.6/site-packages/numpy/core/include -I_deps/libsharp/auto/include -I/home/matth/local/include/python3.6m -c -c fortran/interpol_32.f90 -o build/temp.linux-x86_64-3.6/fortran/interpol_32.o -Jbuild/temp.linux-x86_64-3.6/pixell -Ibuild/temp.linux-x86_64-3.6/pixell -Ofast -fopenmp -Wno-conversion -Wno-tabs" failed with exit status 1
```

To fix this, I changed '-Ofast' to '-O3 -ffast-math' in `extra_f90_compile_args`

**Comment by msyriac** [comment]
Thanks for raising this Matt. @mhasself any thoughts? Is there any benefit in using Ofast as opposed to O3 + ffast-math?

**Comment by mhasself** [comment]
On gfortran, these two flag sets produce identical low-level flag choices (fun with flags: ``gfortran -c -O3 -ffast-math -Q --help=optimizers``).  However, the intel fortran compiler recognizes -Ofast but does not recognize -ffast-math (as far as I can tell from web).  Both compilers accept -O3 but the best translation for ``-ffast-math``, on intel, seems to be ``-no-prec-div -fp-model fast=2``.

Do we have of knowing if user is trying to use gnu vs. intel fortran?

**Comment by msyriac** [comment]
Currently, we ask people who use intel compilers to do:
python setup.py build_ext -i --fcompiler=intelem --compiler=intelem
which works on NERSC for me.
(I don't know of a better solution. Healpy also is not easy to install with intel.  My install command for healpy on NERSC looks like: CXX=icpc CXXL=icpc LDSHARED="icc -shared" CC=icc python setup.py build_ext -i --compiler=intelem -c icc )

which means setup.py can probably inspect sys.argv and appropriately set the compiler flags. Kind of hacky.

**Comment by mhasself** [comment]
Asking users to add stuff to the command line is fine with me... getting them to edit setup.py is bad.  Does this look ok?  It would remove -Ofast from extra_f90_compile_args, but would add it back if the user hasn't specified FCFLAGS.

```
fcflags = os.getenv('FCFLAGS')
if fcflags is None or fcflags.strip() == '':
    fcflags = ['-Ofast']
else:
    print('User supplied fortran flags: ', fcflags)
    print('These will supersede other optimization flags.')
    fcflags = fcflags.split()

compile_opts['extra_f90_compile_args'].extend(fcflags)

```

**Comment by msyriac** [comment]
Mm, but this would mean Intel users would have to specify some additional FCFLAGS to get the same optimization benefits that gnu users would. Is that right? My original suggestion was to have an if then in setup.py that checks for things like --fcompiler=intelem --compiler=intelem, and appropriately set what we think are the best flags for these IF the user has not already provided them.

**Comment by mhasself** [comment]
Right.  But the FCFLAGS solution solves many problems matching "fortran chokes on the optimization flags because ____", including the old-gfortran problem and the intel problem.  Intel compiler users are probably working on some weird cluster, and won't balk at having to set FCFLAGS to get exactly the optimization they want.  Also, compiler flags change around a bit with each release (_ahem_ gcc), and so this provides some degree of future/past-proofing setup.py.

If you still want to go the route of inspecting sys.argv, remember that the following are all valid and equivalent, as far as setup.py is concerned:
  --fcompiler=intelem
  --fcompiler intelem
  --fcomp intelem

:)

**Comment by msyriac** [comment]
Very good points. Thank you for valiantly resisting terrible design suggestions :) Please go ahead and merge this in when you get the chance. I'll update the README appropriately.

**Comment by mhasself** [comment]
Great.  Changes are in commit 6a0a08.

**Comment by msyriac** [comment]
Thanks, closing this pure Mat(t)hew issue.
