### ISSUE TITLE
Incorrect name of error in setup.py

### ISSUE THREAD

**Issue by geetmankar** [simonsobs/pixell#218]
https://github.com/simonsobs/pixell/blob/e6ec521f588eec374a2b6689c6d07af6bdde1dbb/setup.py#L30

The  `raise DistUtilsError('Windows is not supported.')` is supposed to be ` DistutilsError('Windows is not supported.')`, the `U` in `Utils` should be lowercase

**Comment by msyriac** [comment]
Thanks, fixed.
