### ISSUE TITLE
Pixell.enplot function deprecated by Pillow 10

### ISSUE THREAD

**Issue by zatkins2** [simonsobs/pixell#225]
Reposting a good find from [@James11222](https://github.com/James11222) (he may not be a simonsobs member):

> The enplot function is deprecated for versions of Pillow > 9.5.0. In particular, when using the `getsize()` function with respect to fonts in pillow, that function is no longer in use. For newer versions of Pillow the correct function to use now is `getbbox()`
> 
> I link a thread to the post that helped me figure out this issue when setting up my environment. Either enforcing Pillow <= 9.5.0 or fixing the syntax used in Pixell should be updated
> 
> Help Thread: [tensorflow/models#11040](https://github.com/tensorflow/models/issues/11040)

Original issue noted in the DR4_DR5_Notebooks repo: https://github.com/ACTCollaboration/DR4_DR5_Notebooks/issues/49#issue-1890945074

**Comment by amaurea** [comment]
Fixed by pull #232
