### ISSUE TITLE
cmisc breaks readthedocs builds

### ISSUE THREAD

**Issue by mhasself** [simonsobs/pixell#226]
I was trying to look up stuff for pixell.reproject, but the [reference area](https://pixell.readthedocs.io/en/latest/reference.html#reproject-map-reprojection) is blank.

Turns out that reproject.py requires curvedsky, and curvedsky requires cmisc, and cmisc.py is produced through cython.  And I guess that doesn't get run, in a rtd build.

Here's a build log: https://readthedocs.org/projects/pixell/builds/21855747/

Does it still work to check READTHEDOCS envvar and then mock or skip the submodule?  It's only imported from curvedsky.

**Comment by amaurea** [comment]
I'm not familiar with autodoc, so I don't know how to properly fix this. The simplest workaround is probably to just move the cmisc import into the functions that need it. The disadvantage of this is that it delays import errors, so one might think one has everything set up when one doesn't actually. That isn't too big an issue though.

**Comment by msyriac** [comment]
Outside readthedocs, I might prefer an error rather than a warning if something didn't compile. I'll push the first suggestion you made.

**Comment by msyriac** [comment]
Ok, I think all import errors should be fixed now. For future reference, anything you'd rather not have readthedocs install or compile, you should add to this block:
https://github.com/simonsobs/pixell/blob/d3b92ab7ab4fe84530c158c5f7430db19405ec71/docs/conf.py#L87
