### ISSUE TITLE
`enmap_from_healpix` default coordinate transformation throws error

### ISSUE THREAD

**Issue by damonge** [simonsobs/pixell#23]
* pixell version: 0.1.1
* Python version: Python 2.7.13 |Anaconda
* Operating System: Linux (Cori)

### Description
Trying to reproject healpix map to CAR. It seems like the default coordinate transformation doesn't work well.

### What I Did
```
  File "masking.py", line 12, in <module>
    map_enb=reproject.enmap_from_healpix(map_hp,map_en.shape,map_en.wcs,ncomp=3)
  File "/global/homes/d/damonge/.local/cori/2.7-anaconda-4.4/lib/python2.7/site-packages/pixell/reproject.py", line 108, in enmap_from_healpix
    s1,s2 = rot.split(",")
AttributeError: 'list' object has no attribute 'split'
```

**Comment by msyriac** [comment]
Hi David, these were fixed with recent bug patches. I would recommend that you stay on top of master until we have a major version release some time in November. If git pull doesn't fix this, let me know!

**Comment by damonge** [comment]
OK, I had `pip install`ed. Just got the latest master and this is indeed sorted. Thanks!
