### ISSUE TITLE
Mini bug in `get_method`

### ISSUE THREAD

**Issue by damonge** [simonsobs/pixell#245]
https://github.com/simonsobs/pixell/blob/2388e0db2c962fc03fe6f4d7f77863d70eeec7cf/pixell/curvedsky.py#L460

I think there's a bug here, where `map.shape` and `map.wcs` should be just `shape` and `wcs`. It's probably not causing any issues, since `minfo` is almost never `None`, but still.

**Comment by amaurea** [comment]
Well spotted! It will be fixed soon.
