### ISSUE TITLE
Example of using sim_objects

### ISSUE THREAD

**Issue by zonca** [simonsobs/pixell#253]
Would you have a recent example of using `sim_objects` with a catalog like Websky?

I see this script is a couple of years old: https://github.com/amaurea/tenki/blob/master/sim_websky.py, is it still current? or do you have a newer version?

I would like to implement this functionality into PySM and I am wondering if I can use `pixell` and then transform to HEALPix if needed.

For my reference:
https://github.com/simonsobs/pixell/blob/a5e44701c4f63106bc105f48c14d99f8fe233ca9/pixell/pointsrcs.py#L35-L79

**Comment by msyriac** [comment]
Sorry for the delay; I have an example here: https://github.com/msyriac/orphics/blob/9ad016d651e04f67303a6d72a7f4ff154f84f3cc/orphics/maps.py#L15

**Comment by zonca** [comment]
thanks @msyriac , I am impressed on how fast this is...
10000 sources in half a second.

![image](https://github.com/simonsobs/pixell/assets/383090/27706b96-9ce6-445d-9fa6-cfb2564ff32e)

notebook I used: https://gist.github.com/zonca/d18aeca1a65e4531d67df1ca6a45fd96

also for testing purposes, generating a source with a given flux and doing aperture photometry to recover that flux after simulation: https://www.zonca.dev/posts/2024-05-02-pysm-point-source-pixell

**Comment by msyriac** [comment]
Cool!
And yes, all credit to @amaurea (Sigurd Naess) who wrote pretty optimal code for this!
