### ISSUE TITLE
Bug in enplot

### ISSUE THREAD

**Issue by thibautlouis** [simonsobs/pixell#35]
* pixell version: 0.2.0
* Python version: python 2.7
* Operating System: MAC

### Description

bug while calling enplot.get_plots, we trace it back to arial.ttf missing in the build directory of the code located in:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pixell-0.2.0-py2.7-macosx-10.13-x86_64.egg/pixell  on my laptop.
So we should probably handle this in setup.py

**Comment by msyriac** [comment]
Thanks for reporting. This has been fixed in 07f6f264c070a4b64cbfff329c1a6c9638200ec8 (v0.4.6).

**Comment by thibautlouis** [comment]
yep it works now !
