### ISSUE TITLE
Make curvedsky.rand_alm compatible with curvedsky.rand_alm_healpy

### ISSUE THREAD

**Issue by msyriac** [simonsobs/pixell#40]
Currently, they interpret lmax differently.

**Comment by ajvanengelen** [comment]
Just a note on this.  For a 1d input power spectrum `mypower` with length 100, 

(a) The input formats are different: one can do
`
curvedsky.rand_alm(mypower, lmax = lmax)
`
but for `curvedsky.rand_alm_healpy` the inputs have to have shape `(Ncomp, Ncomp, Nell)` so one must do
`
curvedsky.rand_alm_healpy(  mypower[None, None], lmax = lmax) 
`
(b) The resulting lengths are different, and rand_alm_healpy does what I expect. Note the number of alm's should be `\Sum(l + 1)_{l=0}^{lmax} =  (lmax + 1) * (lmax + 2) / 2`.  Only rand_alm_healpy returns a result of that shape.  Example:

```python
def nalm(lmax):
    return (lmax + 1) * (lmax + 2) / 2

lmaxes = [50, 100, 150, 300]

for lmax in lmaxes:
    print "nalm(%i) = %i, curvedsky.rand_alm gives %s, curvedsky.rand_alm_healpy gives %s "\
	% (lmax, \
           nalm(lmax),\
           curvedsky.rand_alm(mypower, lmax = lmax).shape, \
           curvedsky.rand_alm_healpy(  mypower[None, None], lmax = lmax).shape)
```
This gives
```
nalm(50) = 1326, curvedsky.rand_alm gives (1326,), curvedsky.rand_alm_healpy gives (1, 1326) 
nalm(100) = 5151, curvedsky.rand_alm gives (5151,), curvedsky.rand_alm_healpy gives (1, 5151) 
nalm(150) = 11476, curvedsky.rand_alm gives (5151,), curvedsky.rand_alm_healpy gives (1, 11476) 
nalm(300) = 45451, curvedsky.rand_alm gives (5151,), curvedsky.rand_alm_healpy gives (1, 45451) 
```

**Comment by msyriac** [comment]
Thanks for looking into this Alex! So presumably rand_alm_healpy is filling mypower with zeros for mypower.lmax < ell < lmax? I think this is done in ps = powspec.sym_compress(ps, scheme="diag"), and the two functions will treat ps identically if we add that to the top of rand_alm. @amaurea can confirm.

**Comment by msyriac** [comment]
This has been fixed (h/t Sigurd), and I've added a test.
