### ISSUE TITLE
FFT runtime error 

### ISSUE THREAD

**Issue by dwhan89** [simonsobs/pixell#41]
* pixell version: 0.4.6
* Python version: 2.7.13
* Operating System: NERSC Cori (SuSE Linux Enterprise Server (SLES) Linux distribution.)

### Description

Fast fourier transform works on an enmap of shape (1, 1, Nx, Ny). But when I try to take fast Fourier transform of an enmap of shape (2, 1, Nx, Ny), it throw the following runtime error. 

`RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug`

### To Reproduce 

```
In [20]: from pixell import enmap, fft

In [21]: import numpy as np

In [22]: data = enmap.enmap(np.zeros((2,1,2,2)))

In [23]: fft.fft(data[0,:,:,:], axes=[-2, -1])
Out[23]: 
array([[[ 0.+0.j,  0.+0.j],
        [ 0.+0.j,  0.+0.j]]])

In [24]: fft.fft(data[:,:,:,:], axes=[-2, -1])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-24-b0a0683d282a> in <module>()
----> 1 fft.fft(data[:,:,:,:], axes=[-2, -1])

/global/u2/d/dwhan89/cori/workspace/pixell/pixell/fft.pyc in fft(tod, ft, nthread, axes, flags)
     82                 ft  = empty(tod.shape, otype)
     83                 tod = tod.astype(otype, copy=False)
---> 84         plan = engines[engine].FFTW(tod, ft, flags=flags, threads=nt, axes=axes)
     85         plan()
     86         return ft

pyfftw/pyfftw.pyx in pyfftw.pyfftw.FFTW.__cinit__ (/tmp/pip-build-P8fL0W/pyfftw/pyfftw/pyfftw.c:10585)()

RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.
```

### Misc Note

I was talking to Alex about this. He mentioned that the error might have occured because the data is not continuous in memory. 

```
In [25]: data.flags
Out[25]: 
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

```

**Comment by amaurea** [comment]
Crashes with 4d arrays appears to be a bug in intel's emulation of FFTW. On
many clusters, such as niagara, the fftw package actually provides the
intel version instead of the real fftw. This can be good because the intel
version is faster, and doesn't need planning, but it's annoying that it has
this problem.

**Comment by msyriac** [comment]
This is still an issue for Intel fftw right DW?

**Comment by dwhan89** [comment]
Yes, but I closed the issue because this is more of a problem with intel version fftw, than with pixell. Would you like to reopen the issue?

**Comment by msyriac** [comment]
I was just wondering if the Intel issue itself had been fixed. I guess not. This can remain closed, I agree, and good to have it documented, so thanks for raising it.
