### ISSUE TITLE
documentation clarification for postage_stamp width

### ISSUE THREAD

**Issue by vcalafut** [simonsobs/pixell#46]
I'm using the reproject.postage_stamp function, but I'm getting a significantly smaller output map than expected. I wanted to confirm I'm interpreting the 'width_arcmin' input correctly. The documentation says: stamp dimension in arcminutes. What is meant by stamp 'dimension"?

**Comment by msyriac** [comment]
It should be the stamp width "w" in arcminutes, such that it returns a w arcmin x w arcmin stamp. The number of pixels will be approximately int(w/res_arcmin). Does that help? Let us know how the docs can be improved.
