### ISSUE TITLE
h5py API change warning

### ISSUE THREAD

**Issue by msyriac** [simonsobs/pixell#52]
When working with `hdf` files, pixell currently access data through `.value`, but this has been deprecated in h5py. These warnings appear:

```
/home/msyriac/.local/lib/python3.7/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
```

**Comment by ajvanengelen** [comment]
This is apparently no longer just a warning - I just got this as a full-stop error:  



<img width="1108" alt="Screen Shot 2022-06-03 at 17 21 09" src="https://user-images.githubusercontent.com/15734556/171968997-4db40005-fca1-4585-9787-e3c87cfaa972.png">
