### ISSUE TITLE
Supporting Python 2 does not seem to be possible anymore / Let's drop Python 2 support?

### ISSUE THREAD

**Issue by msyriac** [simonsobs/pixell#56]
I have descended into dependency hell and re-emerged with this realization.

pixell depends on both astropy and pytest, both very useful modules. (astropy is required, pytest is nice to have).

astropy famously entirely dropped support for Python 2 with their version >3. astropy v>3 will not install in a Python 2 environment.

astropy also depends on pytest, but astropy <v3 requires the pytest version to be precisely 3.6 for complicated reasons (for reference, pytest is currently on some version >4). See https://github.com/astropy/astropy/issues/8177#issuecomment-471611295  It turns out this version of pytest (3.6) breaks on python 2.7. I am not sure if this is a recent bug; I haven't had the time to dig into the details.

But basically, I think this means: if we want to keep using pytest, we need astropy >3 which needs Python 3. (I'd be happy to be proved wrong)

For the record, I am in favor of dropping Python 2 support: https://pythonclock.org/

**Comment by bsipocz** [comment]
@msyriac - for the record, astropy LTS (2.0.x) is happy with pytest '>=2.8,<3.7', it doesn't need to be version 3.6. Otherwise dropping python2 support is a good way to go, most upstream packages (numpy, matplotlib, etc) are dropping the support, too and their next releases will be python3 only.

**Comment by msyriac** [comment]
Thanks for the clarification, and sorry I misrepresented astropy's requirement. It is in fact the requirement of another package we use (pytest-cov) in combination with astropy that forces us into exactly pytest v3.6.

I also just want to clarify here that "dropping support for Python 2" in the context of this issue doesn't mean that we should (immediately) start reintroducing things that would break in Python 2. I just mean that if we decide to go down this route, when a user tries to install pixell from PyPI, they will get an error stating that Python 3 is required because all the dependencies couldn't be met. The user could always choose to then git clone pixell and use it in whatever environment they already have set up.

**Comment by bsipocz** [comment]
I would argue that there is benefit in removing Python 2 related things, too, it would not just clean up the code base but would make it possible to start using the nice Python 3 features that hasn't been backported to Python 2.7.

**Comment by mhasself** [comment]
I think you should drop python2... Life is going to get increasingly difficult for all python2 hold-outs.  Would you rather help your users to transition now, or see them kick along a python2 pipeline for 2 more years and then have them scrambling to upgrade everything while we're drowning in data?  Pull the plug!  Now is the time!

**Comment by msyriac** [comment]
Totally with you both, but our core developer has not switched to Python 3 fully. He wrote most of this library. If his own code breaks if we drop true Python 2 support (e.g. by using new Python 3 features), then we can't pull the plug just quite yet. Hence, I'm suggesting the temporary compromise of only dropping Python 2 support from the PyPI package / pip installation process (which doesn't affect him). (He should correct me if I'm misstating his position.)
