### ISSUE TITLE
niter in curved sky map2alm

### ISSUE THREAD

**Issue by thibautlouis** [simonsobs/pixell#59]
Hi,

It might be useful to add an option for specifying a number of iteration in the map2alm operation. I have hacked something in PSPy for now but I think it should live in pixell for clarity (and for more people being able to use it).
Let me know if you feel like moving it there. It makes a real difference for lmax>nside 
Cheers,

Thibaut

**Comment by msyriac** [comment]
Thanks Thibaut, I didn't think niter would actually matter for CAR pixelization. I remember @amaurea telling me that for typical CAR choices, quadrature is exact and so iteration is not needed (correct me if I'm wrong -- maybe I'm misremembering why iteration was needed to begin with). But if you're seeing it matters, yes, it would be great to have the option in pixell. Can you submit it as a PR? Or point us to your implementation? Former is preferred of course.

**Comment by thibautlouis** [comment]
I think it matters more for healpix pixellisation so I was referring to the healpix map2alm of curved sky. We could in principle only use healpy but healpy does not allow you to easily do spinned harmonic transform (which is required for pure B modes transform that might be of used for many people). Healpix does but we would like to avoid direct dependency on Healpix if possible.

Iterating should be as simple as:
alm = curvedsky.map2alm(map)
for k in range(niter):
    alm += curvedsky.map2alm(map-curvedsky.alm2map(alm,map))

Since curvedsky allow to do spherical harmonic transform in different pixellisation, I believe it should live there.

**Comment by msyriac** [comment]
Ok, agreed on all this. @amaurea had opinions on where the iteration should be done, so I'm hoping he can implement it.

**Comment by mreineck** [comment]
Just to add another data point here: for `lmax<=1.5*Nside`, specific pixel weights can be applied to the Healpix map, and you get the accurate a_lm without any iteration. See for example https://healpy.readthedocs.io/en/latest/generated/healpy.sphtfunc.map2alm.html

**Comment by msyriac** [comment]
This is now implemented.
