### ISSUE TITLE
Run tests as part of "install"

### ISSUE THREAD

**Issue by msyriac** [simonsobs/pixell#69]
It's my opinion that for pixell, tests should be run at the end of any kind of setup.py "install" procedure. A cursory google search suggests that this breaks from traditional Python packaging practice. But pixell (and I would argue, any Python package that has OpenMP enabled extensions) should be a special case because it is very finicky when it comes to Intel vs GNU inconsistencies -- sometimes when there are multiple openmp libraries present on the system, installation can proceed without any error while the results of function calls can depend on the number of openmp threads (!) because the user has both GNU and Intel modules on the same system.

Can we modify setup.py that the tests usually run by "py.test" are run at the end of "install" (including for an over-the-web "pip install" and for a local "python setup.py install")?

**Comment by mhasself** [comment]
It seems more natural for the check to be done at build time or at run time.  Can a minimal test case be implemented that exercises openmp to see if it's all working properly?  This test could be run whenever pixell is _imported_.  This would be a very powerful level of protection.  And the user could simply set OMP_NUM_THREADS=1 to power through the issue, if needed.

Then if you wanted to run that test after install, it would be as simple as "import pixell" (with the path adjusted appropriately).

**Comment by msyriac** [comment]
Tests can now be run after install with
> test-pixell
