### ISSUE TITLE
enmap.area returns too large area for full sky CAR

### ISSUE THREAD

**Issue by msyriac** [simonsobs/pixell#70]
The result is 23% lager than 4pi regardless of resolution and nsub.

**Comment by mhasself** [comment]
@msyriac If you post example code (generate the map, print out its area), I'd be happy to work on this.  I have the relevant geometry stuff in personal RAM right now.

**Comment by msyriac** [comment]
Here is an example line for the ratio of the area of a full sky geometry to 4pi:
```
>>> enmap.area(*enmap.fullsky_geometry(res=0.0001))/4/np.pi
1.2317585411101402
```
