### ISSUE TITLE
reproject.enmap_from_healpix "unit" kwarg handling

### ISSUE THREAD

**Issue by zatkins2** [simonsobs/pixell#95]
* pixell version: 0.8.0
* Python version: 3.8.2
* Operating System: Ubuntu 20.04

### Description

unit kwarg of reproject.enmap_from_healpix not applied to hp_map if hp_map is supplied as a string containing the path to the file (lines 211-217 of reproject.py).

### Comment

just a tiny thing!

**Comment by msyriac** [comment]
Nice find Zach, thanks! I just fixed the indentation.
